glance:
  MYSQL_SERVER: localhost
  GLANCE_IP: 10.105.12.205
  GLANCE_DB_USER: glance
  GLANCE_DB_NAME: glance
  GLANCE_DB_PASS: glance
  DB_ALLOW: glance.*
  HOST_ALLOW: localhost
  RABBITMQ_HOST: 10.105.12.205
  RABBITMQ_PORT: 5672
  RABBITMQ_USER: openstack
  RABBITMQ_PASS: rabbit
  AUTH_KEYSTONE_HOST: 10.105.12.205
  AUTH_KEYSTONE_PORT: 35357
  AUTH_KEYSTONE_PROTOCOL: http
  AUTH_GLANCE_ADMIN_TENANT: service
  AUTH_GLANCE_ADMIN_USER: glance
  AUTH_GLANCE_ADMIN_PASS: glance
