glance:
  MYSQL_SERVER: controller
  GLANCE_IP: 172.16.0.1
  GLANCE_DB_USER: glance
  GLANCE_DB_NAME: glance
  GLANCE_DB_PASS: glance
  DB_ALLOW: glance.*
  HOST_ALLOW: 172.16.0.0/255.255.0.0
  RABBITMQ_HOST: 172.16.0.1
  RABBITMQ_PORT: 5672
  RABBITMQ_USER: openstack
  RABBITMQ_PASS: rabbit
  AUTH_KEYSTONE_HOST: 172.16.0.1
  AUTH_KEYSTONE_PORT: 35357
  AUTH_KEYSTONE_PROTOCOL: http
  AUTH_GLANCE_ADMIN_TENANT: service
  AUTH_GLANCE_ADMIN_USER: glance
  AUTH_GLANCE_ADMIN_PASS: glance
