keystone:
  MYSQL_SERVER: controller
  KEYSTONE_IP: 10.0.1.11
  KEYSTONE_ADMIN_TOKEN: ADMIN
  KEYSTONE_ADMIN_TENANT: admin
  KEYSTONE_ADMIN_USER: admin
  KEYSTONE_ADMIN_PASSWD: admin
  KEYSTONE_ROLE_NAME: admin
  KEYSTONE_AUTH_URL: http://10.0.1.11:35357/v3
  KEYSTONE_DB_NAME: keystone
  KEYSTONE_DB_USER: keystone
  KEYSTONE_DB_PASS: keystone
  DB_ALLOW: keystone.*
  HOST_ALLOW: 10.0.0.0/255.0.0.0

