keystone:
  MYSQL_SERVER: localhost
  KEYSTONE_IP: 10.105.12.205
  KEYSTONE_ADMIN_TOKEN: ADMIN
  KEYSTONE_ADMIN_TENANT: admin
  KEYSTONE_ADMIN_USER: admin
  KEYSTONE_ADMIN_PASSWD: admin
  KEYSTONE_ROLE_NAME: admin
  KEYSTONE_AUTH_URL: http://10.105.12.205:35357/v3
  KEYSTONE_DB_NAME: keystone
  KEYSTONE_DB_USER: keystone
  KEYSTONE_DB_PASS: keystone
  DB_ALLOW: keystone.*
  HOST_ALLOW: localhost

