keystone:
  MYSQL_SERVER: controller
  KEYSTONE_IP: 172.16.0.223
  KEYSTONE_ADMIN_TOKEN: ADMIN
  KEYSTONE_ADMIN_TENANT: admin
  KEYSTONE_ADMIN_USER: admin
  KEYSTONE_ADMIN_PASSWD: admin
  KEYSTONE_ROLE_NAME: admin
  KEYSTONE_AUTH_URL: http://172.16.0.223:35357/v3
  KEYSTONE_DB_NAME: keystone
  KEYSTONE_DB_USER: keystone
  KEYSTONE_DB_PASS: keystone
  DB_ALLOW: keystone.*
  HOST_ALLOW: 172.0.0.0/255.0.0.0

